### ISSUE TITLE
Profile Descriptions

### ISSUE THREAD

**Issue by juniirz** [Saighedd/SynPro#1]
For some reason, when i go to someone's profile, sometimes it just shortens their profile and it's really annoying when i wanna see their full description, for example https://www.syntax.eco/users/4449/profile
it should say:
🗣️I'm not yapping. 💀
Currently grinding following! | Progress: ID 158 | Goal: Follow 100 people a day.
If you want to be my friend, just send a friend request, i'm kinda lonely!
but instead it says:
🗣️I'm not yapping. 💀

Cur...

If ...
Again, very annoying

**Comment by juniirz** [comment]
(not the only thing that is shortened)

**Comment by Saighedd** [comment]
If you update the userscript this should be a fix, if not lmk.
